name: PMC-Location-API
version: '1.0'
main: fr.sukikui.pmc_location_api.Main
api-version: '1.21'
authors: [ Sukikui ]
description: REST API to get players locations from the server Play-MC.fr using a key
